services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping || rabbitmqctl -q status > /dev/null 2>&1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  
  
  autocatalogdb:
    container_name: autocatalogdb
    restart: always
    environment:
      - POSTGRES_USER=${AUTOCATALOG_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTOCATALOG_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTOCATALOG_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - auto-catalog-postgres:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTOCATALOG_POSTGRES_USER} -d ${AUTOCATALOG_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  
  adservicedb:
    container_name: adservicedb
    restart: always
    environment:
      - POSTGRES_USER=${ADSERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ADSERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ADSERVICE_POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - ad-service-postgres:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ADSERVICE_POSTGRES_USER} -d ${ADSERVICE_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  profileservicedb:
    container_name: profileservicedb
    restart: always
    environment:
      - POSTGRES_USER=${PROFILESERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PROFILESERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${PROFILESERVICE_POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - profile-service-postgres-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PROFILESERVICE_POSTGRES_USER} -d ${PROFILESERVICE_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  
  redis:
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  
  
  autocatalog.web:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__AppDbContext=Server=${AUTOCATALOG_POSTGRES_SERVER};Port=5432;Database=${AUTOCATALOG_POSTGRES_DB};Username=${AUTOCATALOG_POSTGRES_USER};Password=${AUTOCATALOG_POSTGRES_PASSWORD}
      - Authentication__MetadataAddress=http://keycloak:8080/realms/carsale/.well-known/openid-configuration
      - Authentication__ValidIssuer=http://localhost:8080/realms/carsale
      - FileStorage__Endpoint=https://filemanagement.grpc:8081
      - RabbitMQ__Host=amqp://rabbitmq:5672
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets/:/home/app/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/https/:/https/
    depends_on:
      autocatalogdb:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      filemanagement.grpc:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  
  adservice.web:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__AppDbContext=Server=${ADSERVICE_POSTGRES_SERVER};Port=5432;Database=${ADSERVICE_POSTGRES_DB};Username=${ADSERVICE_POSTGRES_USER};Password=${ADSERVICE_POSTGRES_PASSWORD}
      - ConnectionStrings__Redis=redis:6379
      - FileStorage__Endpoint=https://filemanagement.grpc:8081
      - RabbitMQ__Host=amqp://rabbitmq:5672
      - Authentication__MetadataAddress=http://keycloak:8080/realms/carsale/.well-known/openid-configuration
      - Authentication__ValidIssuer=http://localhost:8080/realms/carsale
      - AutoCatalog__Endpoint=https://autocatalog.web:8081
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets/:/home/app/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/https/:/https/
    depends_on:
      adservicedb:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      redis:
        condition: service_healthy
      filemanagement.grpc:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  
  keycloakdb:
    container_name: keycloakdb
    restart: always
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - keycloak-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${KEYCLOAK_POSTGRES_USER} -d ${KEYCLOAK_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  keycloak:
    restart: always
    command: >
      start
      --import-realm
      --https-port=8443
      --http-port=8080
      --http-enabled=true
      --hostname-strict=false
      --https-key-store-file=/opt/keycloak/conf/server.keystore
      --https-key-store-password=password
    entrypoint: >
      /bin/bash -c "
      if ! keytool -list -alias server -keystore /opt/keycloak/conf/server.keystore -storepass password > /dev/null 2>&1; then
        keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname 'CN=keycloak' -alias server -ext 'SAN:c=DNS:keycloak,DNS:localhost,IP:127.0.0.1' -keystore /opt/keycloak/conf/server.keystore;
      fi &&
      /opt/keycloak/bin/kc.sh $$@
      " --
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: kc-admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: 1111
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${KEYCLOAK_POSTGRES_SERVER}:5432/${KEYCLOAK_POSTGRES_DB}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      keycloakdb:
        condition: service_healthy
    volumes:
      - ./keycloak/realm/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
      - keycloak-keystore:/opt/keycloak/conf
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 180s
  
  minio:
    container_name: minio
    restart: always
    ports:
      - "9000:9000"   # API (HTTP)
      - "9001:9001"   # Console (HTTP)
    environment:
      MINIO_ROOT_USER: admin       # >= 3 chars
      MINIO_ROOT_PASSWORD: password  # >= 8 chars
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:9000/minio/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  createbuckets:
    restart: on-failure:5
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 admin password;
      /usr/bin/mc mb myminio/ad-service;
      /usr/bin/mc mb myminio/auto-catalog;
      /usr/bin/mc mb myminio/profile-service;
      /usr/bin/mc policy set public myminio/ad-service;
      /usr/bin/mc policy set public myminio/auto-catalog;
      /usr/bin/mc policy set public myminio/profile-service;
      exit 0;
      "
    depends_on:
      minio:
        condition: service_healthy
  
  
  filemanagement.grpc:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__FileManagementDbContext=Data Source=/app/data/filedb
      - Minio__Endpoint=minio:9000
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets/:/home/app/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/https/:/https/
      - file-management-data:/app/data/
    depends_on:
      minio:
        condition: service_healthy
      createbuckets:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  
  profileservice.api:
    restart: always
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=carsale
      - KEYCLOAK_CLIENT_ID=profile-service
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_ADMIN_SECRET}
      - KEYCLOAK_BASE_URL=http://keycloak:8080
      - KEYCLOAK_AUTH_REALM=carsale

      - KEYCLOAK_ADMIN_CLIENT=profile-service
      - KEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_ADMIN_SECRET=${KEYCLOAK_ADMIN_SECRET}

      - PROFILESERVICE_POSTGRES_PORT=5432
      - PROFILESERVICE_POSTGRES_USER=${PROFILESERVICE_POSTGRES_USER}
      - PROFILESERVICE_POSTGRES_PASSWORD=${PROFILESERVICE_POSTGRES_PASSWORD}
      - PROFILESERVICE_POSTGRES_HOST=${PROFILESERVICE_POSTGRES_SERVER}
      - PROFILESERVICE_POSTGRES_DB=${PROFILESERVICE_POSTGRES_DB}
      - PROFILESERVICE_POSTGRES_URL=postgresql://${PROFILESERVICE_POSTGRES_USER}:${PROFILESERVICE_POSTGRES_PASSWORD}@${PROFILESERVICE_POSTGRES_SERVER}:5432/${PROFILESERVICE_POSTGRES_DB}
    ports:
      - "4000:4000"
    depends_on:
      profileservicedb:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      filemanagement.grpc:
        condition: service_healthy


configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."
