services:
  
  rabbitmq:
    image: rabbitmq:latest
    
  autocatalogdb:
    image: postgres:17
    
  adservicedb:
    image: postgres:17
    
  redis:
    image: redis:latest
    
  autocatalog.web:
    image: autocatalog.web
    build:
      context: .
      dockerfile: src/Services/AutoCatalog/AutoCatalog.Web/Dockerfile
      
  adservice.web:
    image: adservice.web
    build:
      context: .
      dockerfile: src/Services/AdService/AdService.Web/Dockerfile
      
  keycloak:
    build:
      context: .
      dockerfile: keycloak/Dockerfile
    
  keycloakdb:
    image: postgres:17
    
  minio:
    image: minio/minio:latest
    
  createbuckets:
    image: minio/mc
    
  filemanagement.grpc:
    image: filemanagement.grpc
    build:
      context: .
      dockerfile: src/Services/FileManagement/FileManagement.Grpc/Dockerfile
      
  profileservicedb:
    image: postgres:17
    
  profileservice.api:
    image: profileservice.api
    build:
      context: .
      dockerfile: src/Services/ProfileService/Dockerfile
      args:
        PROFILESERVICE_POSTGRES_URL: postgresql://${PROFILESERVICE_POSTGRES_USER}:${PROFILESERVICE_POSTGRES_PASSWORD}@${PROFILESERVICE_POSTGRES_SERVER}:5432/${PROFILESERVICE_POSTGRES_DB}
  
      
      
volumes:
  auto-catalog-postgres:
  ad-service-postgres:
  profile-service-postgres-data:
  keycloak-data:
  keycloak-keystore:
  file-management-data:
  minio-data:
    driver: local
  redis-data:
    driver: local
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  
  
  

