// <auto-generated />
using System;
using System.Collections.Generic;
using AdService.Infrastructure.Postgres.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdService.Infrastructure.Postgres.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251219051121_NullableProperties")]
    partial class NullableProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdCarOption", b =>
                {
                    b.Property<Guid>("AdId")
                        .HasColumnType("uuid");

                    b.Property<int>("CarOptionsId")
                        .HasColumnType("integer");

                    b.HasKey("AdId", "CarOptionsId");

                    b.HasIndex("CarOptionsId");

                    b.ToTable("AdCarOption");
                });

            modelBuilder.Entity("AdService.Domain.Aggregates.Ad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<Guid>>("_images")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("Images");

                    b.HasKey("Id");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("AdService.Domain.Entities.CarOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicalName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CarOptions");
                });

            modelBuilder.Entity("AdService.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AdId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AdCarOption", b =>
                {
                    b.HasOne("AdService.Domain.Aggregates.Ad", null)
                        .WithMany()
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdService.Domain.Entities.CarOption", null)
                        .WithMany()
                        .HasForeignKey("CarOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdService.Domain.Aggregates.Ad", b =>
                {
                    b.OwnsOne("AdService.Domain.ValueObjects.CarSnapshot", "Car", b1 =>
                        {
                            b1.Property<Guid>("AdId")
                                .HasColumnType("uuid")
                                .HasColumnName("AdId");

                            b1.Property<Guid>("CarId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BodyType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Color")
                                .HasColumnType("text");

                            b1.Property<decimal?>("Consumption")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("DriveType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FuelType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Generation")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("HorsePower")
                                .HasColumnType("integer");

                            b1.Property<int?>("Mileage")
                                .HasColumnType("integer");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TransmissionType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Vin")
                                .HasColumnType("text");

                            b1.Property<int?>("Year")
                                .HasColumnType("integer");

                            b1.HasKey("AdId", "CarId");

                            b1.HasIndex("AdId")
                                .IsUnique();

                            b1.ToTable("CarSnapshots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AdId");
                        });

                    b.OwnsOne("AdService.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("AdId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasColumnType("text");

                            b1.Property<string>("Region")
                                .HasColumnType("text");

                            b1.HasKey("AdId");

                            b1.ToTable("AdLocations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AdId");
                        });

                    b.OwnsOne("AdService.Domain.ValueObjects.ModerationResult", "ModerationResult", b1 =>
                        {
                            b1.Property<Guid>("AdId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DecidedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DenyReason")
                                .HasColumnType("text")
                                .HasColumnName("DenyReason");

                            b1.Property<string>("Message")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ModeratorMessage");

                            b1.Property<Guid>("ModeratorId")
                                .HasColumnType("uuid")
                                .HasColumnName("ModeratorId");

                            b1.HasKey("AdId");

                            b1.ToTable("Ads");

                            b1.WithOwner()
                                .HasForeignKey("AdId");
                        });

                    b.OwnsOne("AdService.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("AdId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("Amount");

                            b1.HasKey("AdId");

                            b1.ToTable("AdPrices", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AdId");

                            b1.OwnsOne("AdService.Domain.ValueObjects.Currency", "Currency", b2 =>
                                {
                                    b2.Property<Guid>("MoneyAdId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("CurrencyCode")
                                        .HasColumnType("text")
                                        .HasColumnName("Price_CurrencyCode");

                                    b2.HasKey("MoneyAdId");

                                    b2.ToTable("AdPrices");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyAdId");
                                });

                            b1.Navigation("Currency");
                        });

                    b.OwnsOne("AdService.Domain.ValueObjects.SellerSnapshot", "Seller", b1 =>
                        {
                            b1.Property<Guid>("AdId")
                                .HasColumnType("uuid")
                                .HasColumnName("AdId");

                            b1.Property<Guid>("SellerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("RegistrationDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("AdId", "SellerId");

                            b1.HasIndex("AdId")
                                .IsUnique();

                            b1.ToTable("SellerSnapshots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AdId");
                        });

                    b.Navigation("Car");

                    b.Navigation("Location");

                    b.Navigation("ModerationResult");

                    b.Navigation("Price");

                    b.Navigation("Seller")
                        .IsRequired();
                });

            modelBuilder.Entity("AdService.Domain.Entities.Comment", b =>
                {
                    b.HasOne("AdService.Domain.Aggregates.Ad", null)
                        .WithMany("Comments")
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AdService.Domain.Aggregates.Ad", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
