// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProfileService.Infrastructure.Postgres.Data;

#nullable disable

namespace ProfileService.Infrastructure.Postgres.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903084928_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProfileService.Domain.Aggregates.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Picture")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("ProfileService.Domain.Aggregates.UserProfile", b =>
                {
                    b.OwnsMany("ProfileService.Domain.ValueObjects.AdSnapshot", "Ads", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("UserProfileId");

                            b1.Property<string>("AdId")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("UserProfileId", "AdId");

                            b1.ToTable("AdSnapshots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");

                            b1.OwnsOne("ProfileService.Domain.ValueObjects.CarSnapshot", "Car", b2 =>
                                {
                                    b2.Property<Guid>("AdSnapshotUserProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("AdSnapshotAdId")
                                        .HasColumnType("character varying(50)");

                                    b2.Property<string>("BodyType")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Car_BodyType");

                                    b2.Property<string>("Brand")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("Car_Brand");

                                    b2.Property<string>("DriveType")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Car_DriveType");

                                    b2.Property<double>("EngineVolume")
                                        .HasPrecision(18, 1)
                                        .HasColumnType("double precision")
                                        .HasColumnName("Car_EngineVolume");

                                    b2.Property<string>("FuelType")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Car_FuelType");

                                    b2.Property<string>("Generation")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("Car_Generation");

                                    b2.Property<string>("Model")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("Car_Model");

                                    b2.Property<string>("TransmissionType")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Car_TransmissionType");

                                    b2.Property<int>("Year")
                                        .HasColumnType("integer")
                                        .HasColumnName("Car_Year");

                                    b2.HasKey("AdSnapshotUserProfileId", "AdSnapshotAdId");

                                    b2.ToTable("AdSnapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("AdSnapshotUserProfileId", "AdSnapshotAdId");
                                });

                            b1.OwnsOne("ProfileService.Domain.ValueObjects.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("AdSnapshotUserProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("AdSnapshotAdId")
                                        .HasColumnType("character varying(50)");

                                    b2.Property<int>("Amount")
                                        .HasColumnType("integer")
                                        .HasColumnName("Price_Amount");

                                    b2.HasKey("AdSnapshotUserProfileId", "AdSnapshotAdId");

                                    b2.ToTable("AdSnapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("AdSnapshotUserProfileId", "AdSnapshotAdId");

                                    b2.OwnsOne("ProfileService.Domain.ValueObjects.Currency", "Currency", b3 =>
                                        {
                                            b3.Property<Guid>("MoneyAdSnapshotUserProfileId")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("MoneyAdSnapshotAdId")
                                                .HasColumnType("character varying(50)");

                                            b3.Property<string>("Code")
                                                .IsRequired()
                                                .HasMaxLength(3)
                                                .HasColumnType("character varying(3)")
                                                .HasColumnName("Price_CurrencyCode");

                                            b3.HasKey("MoneyAdSnapshotUserProfileId", "MoneyAdSnapshotAdId");

                                            b3.ToTable("AdSnapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("MoneyAdSnapshotUserProfileId", "MoneyAdSnapshotAdId");
                                        });

                                    b2.Navigation("Currency")
                                        .IsRequired();
                                });

                            b1.Navigation("Car");

                            b1.Navigation("Price");
                        });

                    b.OwnsOne("ProfileService.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email_Value");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("ProfileService.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("E164")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber_E164");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("Ads");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
